### ISSUE TITLE
Zero-shot results

### ISSUE THREAD

**Issue by DRSY** [AndresPMD/Clip_CMR#1]
Hi

Thanks for the share of code and reported results. I have tried text-to-image retrieval on MS COCO 1K test split in a zero-shot manner, the results are 46.9/77.3/87.3 for R@1/R@5/R@10 respectively.  It seems that only finetuning the added non-linearity brings negligible improvement? Also, the zero-shot CLIP results on COCO 5k test split reported in the paper "Scaling Up Visual and Vision-Language Representation Learning With Noisy Text Supervision"  are 37.8/62.4/72.2. I cannot reproduce the results using the official CLIP checkpoint.

**Comment by AndresPMD** [comment]
@DRSY 

In my experience, adding a non-linearity improves significantly the results. You can try training the code on this repo and show your results. 
Additionally, the weights released by Open AI are suboptimal models. The best model is not released so achieving the official paper results might not be possible with current open weights.

In case you are interested, the current SOA on Image-Text Matching is achieved by this paper: 

Align before Fuse: Vision and Language Representation Learning with Momentum Distillation - https://arxiv.org/abs/2107.07651

It surpasses Align and CLIP.

Cheers!
